---
- hosts: localhost
  gather_facts: no
  vars:
    image_name: docker.io/nginx:latest
    container_name: nginx
  tasks:
    - name: Create Nginx Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - 80:8000
        timeout: 60
      
