---
  - name: Create Nginx Container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name_nginx }}"
      state: started
      ports:
        - 8088:80
      timeout: 60
      
