---
# tasks file for wp
- name: Create Wordpress Document
  docker_service:
    project_name: Wordpress
    definition:
      version: "2"
      services:
        db:
          image: "{{ mysql_image }}"
          volumes:
            - db_data:/var/lib/mysql
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        wordpress:
          depends_on:
            - db
          image: "{{ wordpress_image }}"
          ports:
            - "{{ http }}"
          restart: always
          environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
      volumes:
        db_data: {}
